fix: decode parameters if needed
proxmoxer/proxmoxer pull request #189
Opened 2024-11-22 23:25 UTC by asdorsey

Fixes #188

2024-11-23 17:00 UTC, jhollowe commented
Please add tests for this new functionality

2024-11-25 17:38 UTC, asdorsey commented
Test added, it's basically a copy of `test_request_data` but with the data value in bytes format.

2024-12-11 04:23 UTC, jhollowe requested changes
Looks good except for the needed formatting fix

2024-12-11 04:23 UTC, jhollowe commented on tests/test_command_base.py
> +        resp = self._session.request("GET", self.base_url + "/fake/echo", data={"key": b"bytes-value"})
Please resolve the formatter/linter CI failures

2024-12-13 16:58 UTC, merged